### ISSUE TITLE
[Deployment] Redirect the default port of browser to the development site

### ISSUE THREAD

**Issue by tai271828** [OH-SHOWN/ohshown-backend#28]
So we won't have to input port numbers in our browser. This will be "demo friendly".

**Comment by EagleC0318** [comment]
@tai271828
Sounds like to change the demo site ip address mapping to `ohshown.site:80` instead of  `ohshown.site:8080`.
But not sure how to do that?

**Comment by tai271828** [comment]
Yes!
> @tai271828 Sounds like to change the demo site ip address mapping to `ohshown.site:80` instead of `ohshown.site:8080`. But not sure how to do that?

**Comment by tai271828** [comment]
By using nginx with the following config, now `http://ohshown.site` is working.

```
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        server_name ohshown.site;

        location / {
            root /home/dev/ohshown-frontend/dist;
            try_files $uri @rewrite;
        }

        location /api/ {
            proxy_pass  http://localhost:8888/api/;
        }

        location @rewrite {
            rewrite ^(.*)$ /index.html last;          
        }
}
```
