### ISSUE TITLE
Add new field (發現地點描述、日期時間) in Ohshown Events of django damin console

### ISSUE THREAD

**Issue by diaoga** [OH-SHOWN/ohshown-backend#34]
**Is your feature request related to a problem? Please describe.**
We need new field in Ohshown Events of django damin console according to #14

**Describe the solution you'd like**
Add new field
- [ ] 發現地點描述 (例如步道里程、與特定地標相對位置和距離等)
- [ ] 發現的日期及時間

**Comment by tai271828** [comment]
I am currently working on this issue, and this pull request complete the task partially https://github.com/OH-SHOWN/ohshown-backend/pull/57 . Date and time are expected to complete after landing this pull request https://github.com/OH-SHOWN/ohshown-backend/pull/58
