### ISSUE TITLE
development site: "CSRF Failed: CSRF token missing or incorrect" when posting with domain ohshown.site

### ISSUE THREAD

**Issue by tai271828** [OH-SHOWN/ohshown-backend#64]
**Describe the bug**
When creating ohshown event with the domain `ohshown.site`, the posting will fail and get "CSRF Failed: CSRF token missing or incorrect".

**To Reproduce**
1. Go to the development site
2. Create an ohshown event as usual

**Expected behavior**
Created ohshown event.

**Additional context**
1. If we use the url with IP, it will be successful
2. Get the message  "CSRF Failed: CSRF token missing or incorrect" with your browser in development mode. Take chrome as example, press `F12`, then go to `Network`, and then check `preview` or `Response`.

![Selection_124](https://user-images.githubusercontent.com/3217432/172333101-7e610b0b-88a8-458e-97b2-5e64c04fe2f6.png)

**Comment by tai271828** [comment]
fwiw, I thought it was `ALLOWED_HOSTS` issue.

**Comment by tai271828** [comment]
hypothesis: this seems to be raised by the approach of docker container deployment. That said, POST to `ohshown.site` may change domain from `ohshown.site` to `localhost` when creating ohshown events.

Next step:
1. check if `vue.config.js` makes sense (frontend)
2. check if CSRF manipulation makes sense in django (backend)

fwiw:
Both settings below could reproduce the issue:

```
diff --git a/vue.config.js b/vue.config.js
index 0c5fdb6..0ebc773 100644
--- a/vue.config.js
+++ b/vue.config.js
@@ -4,7 +4,7 @@ module.exports = {
     disableHostCheck: true,
     proxy: {
       '/server': {
-        target: 'http://localhost:8888',
+        target: 'http://ohshown.site:8888',
         changeOrigin: true,
         pathRewrite: {
           '^/server': ''
```

**Comment by tai271828** [comment]
I am still figuring out what's going on. Currently I use postman to help me debug. Let me brief the approach here for anyone who may be interested in:

1. get the payload from your browser (see below for chrome as example)
2. post the payload in the raw-JSON of postman
![Selection_125](https://user-images.githubusercontent.com/3217432/172375642-3a63bc93-235f-45dd-870d-b97dd54d213b.png)
![Selection_126](https://user-images.githubusercontent.com/3217432/172375688-4a3bee15-1117-4901-a15b-80af2b16a5ed.png)

**Comment by tai271828** [comment]
Direct post via postman and port 8888 works properly. That said, CSRF is not warned by django.

My possible next step: focus on how vue deals with the proxy with the corresponding `.env`.


> I am still figuring out what's going on. Currently I use postman to help me debug. Let me brief the approach here for anyone who may be interested in:
> 
> 1. get the payload from your browser (see below for chrome as example)
> 2. post the payload in the raw-JSON of postman
>    ![Selection_125](https://user-images.githubusercontent.com/3217432/172375642-3a63bc93-235f-45dd-870d-b97dd54d213b.png)
>    ![Selection_126](https://user-images.githubusercontent.com/3217432/172375688-4a3bee15-1117-4901-a15b-80af2b16a5ed.png)

**Comment by tai271828** [comment]
@Neilxx @yanghaochang104  I am a bit blocked and confused by this. If you are familiar with the settings of `vue.config.js`. Do you have any idea about this issue?

> Direct post via postman and port 8888 works properly. That said, CSRF is not warned by django.
> 
> My possible next step: focus on how vue deals with the proxy with the corresponding `.env`.
> 
> > I am still figuring out what's going on. Currently I use postman to help me debug. Let me brief the approach here for anyone who may be interested in:
> > 
> > 1. get the payload from your browser (see below for chrome as example)
> > 2. post the payload in the raw-JSON of postman
> >    ![Selection_125](https://user-images.githubusercontent.com/3217432/172375642-3a63bc93-235f-45dd-870d-b97dd54d213b.png)
> >    ![Selection_126](https://user-images.githubusercontent.com/3217432/172375688-4a3bee15-1117-4901-a15b-80af2b16a5ed.png)

**Comment by Neilxx** [comment]
@tai271828  I'm a little bit confused.
I just post successfully on development site.

![截圖 2022-06-09 上午8 26 57](https://user-images.githubusercontent.com/22217185/172739374-15ad4852-3f2f-4a71-ba9d-4b79f1b9ccca.png)

Am I reproduce the issue correctly?

**Comment by tai271828** [comment]
@Neilxx thanks for retesting. You really save my day lollllllllllllllllll

**Comment by tai271828** [comment]
Just for the record: the issue happened to me again today, but switching to the other profile of my chrome still works. Hooray!
